In [4]:
import numpy as np

In [5]:
a=[1,2,3]

In [6]:
a

[1, 2, 3]

In [7]:
myarr=np.array(a)

In [8]:
print(myarr)

[1 2 3]


In [9]:
import numpy as np
a=[]
n=int(input("enter size of the array"))
for i in range(n):
    val=int(input("enter number"))
    a.append(val)
myarray=np.array(a)
print(myarray)

enter size of the array4
enter number1
enter number2
enter number3
enter number4
[1 2 3 4]


In [10]:
import numpy as np

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
myarray=np.array(a)

In [13]:
print(myarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
myarray.ndim

2

In [15]:
myarray.shape

(3, 3)

In [16]:
array= np.zeros((2,3))

In [17]:
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [146]:
array1=np.array(5)
print(array1)

5


In [19]:
array1

array(5)

In [20]:
array2=np.ones(4)

In [21]:
array2

array([1., 1., 1., 1.])

In [22]:
array3=np.eye(3,3)

In [23]:
array3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
array4=np.diag([1,2,3,4])
array4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [25]:
np.diag(array4)

array([1, 2, 3, 4])

In [26]:
array5=np.random.randint(1,10,3)

In [27]:
array5

array([6, 4, 1])

In [28]:
import numpy as np
a=[]
size=int(input("Enter the number"))
for i in range(size):
    val=int(input("enter the number"))
    a.append(val)
arr=np.array(a)
for i in range(arr.size):
    print(arr[i])
sum=0
for i in range(arr.size):
    sum=sum+arr[i]
print("sum of array",sum)
array1=arr[2:4]
print(array1)

Enter the number3
enter the number3
enter the number4
enter the number5
3
4
5
sum of array 12
[5]


#reshaping

In [29]:
import numpy as np
arr=np.random.randint(1,50,12)
arr=arr.reshape(3,4)

In [30]:
print(arr)

[[25 38  1  6]
 [ 9 49 23 29]
 [31 37 25 12]]


In [31]:
arr=arr.reshape(12)

In [32]:
arr

array([25, 38,  1,  6,  9, 49, 23, 29, 31, 37, 25, 12])

In [33]:
arr.ndim

1

In [34]:
arr.shape

(12,)

In [35]:
#seed_function

In [36]:
import numpy as np

In [37]:
np.random.seed(1)
arr=np.random.randint(1,100,10)

In [38]:
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [39]:
arr.size

10

In [40]:
arr.ndim

1

In [41]:
arr.shape

(10,)

In [42]:
arr=arr.reshape(5,2)

In [43]:
arr

array([[38, 13],
       [73, 10],
       [76,  6],
       [80, 65],
       [17,  2]])

In [44]:
arr[[1,1]]

array([[73, 10],
       [73, 10]])

In [45]:
import numpy as np

In [46]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a[:2,1:3]

array([[2, 3],
       [5, 6]])

In [50]:
import numpy as np
arr=np.random.seed(111)
arr=np.random.randint(1,500,30).reshape(6,5)

In [51]:
arr

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [52]:
arr[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [53]:
#SLICING

In [54]:
import numpy as np

In [55]:
a=np.array([10,20,30,40,50,60,70,80])

In [56]:
slicing=a[3:6]

In [57]:
slicing[:]=0

In [58]:
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [59]:
slicing=a[3:6].copy()

In [60]:
slicing[:]=0

In [61]:
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [62]:
#conditional selection

In [63]:
arr=np.arange(1,16)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [66]:
b=arr>10

In [67]:
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [68]:
arr[b]

array([11, 12, 13, 14, 15])

In [69]:
c=arr[arr%2==0]

In [70]:
c

array([ 2,  4,  6,  8, 10, 12, 14])

In [71]:
import numpy as np

In [72]:
arr=np.arange(1,5)

In [73]:
arr**2

array([ 1,  4,  9, 16], dtype=int32)

In [74]:
arr/0

<ipython-input-74-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([inf, inf, inf, inf])

In [75]:
import numpy as np

In [76]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)

In [77]:
a

array([[1, 2],
       [3, 4]])

In [78]:
b

array([[5, 6],
       [7, 8]])

In [79]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [80]:
a+b

array([[ 6,  8],
       [10, 12]])

In [81]:
b-a

array([[4, 4],
       [4, 4]])

In [82]:
a*b

array([[ 5, 12],
       [21, 32]])

In [83]:
#Some important function in numpy

In [84]:
import numpy as np

In [85]:
arr=np.array([10,20,30,40,50])

In [86]:
arr

array([10, 20, 30, 40, 50])

In [87]:
np.min(arr) #returns min Value

10

In [88]:
np.max(arr) #returns Max Value

50

In [89]:
np.argmin(arr) #postion of min number

0

In [90]:
np.argmax(arr) #postion of max number

4

In [91]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [92]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [93]:
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

In [94]:
np.linspace(1,2,5) #returns value between a given range and with same gap between consecutive elememts.

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [95]:
import numpy as np
np.random.rand(122)
matrix=np.random.randint(1,21,9).reshape(3,3)
matrix

array([[10, 10,  3],
       [20,  7,  3],
       [ 6, 20, 20]])

In [96]:
np.sum(matrix, axis=0)

array([36, 37, 26])

In [97]:
np.min(matrix, axis=1)

array([3, 3, 6])

In [98]:
np.max(matrix)

20

In [99]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,9)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11])

In [100]:
np.random.shuffle(arr) #shuffle the array

In [101]:
arr

array([13, 16,  3, 11, 13, 17, 11, 16, 16])

In [102]:
np.unique(arr) #display unique number of array

array([ 3, 11, 13, 16, 17])

In [103]:
np.unique(arr).size #count the unique count of elements

5

In [104]:
#Stacking 2D array with fixed datatype

In [105]:
import numpy as np
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])
arr1
arr2

array([ 6,  7,  8,  9, 10])

In [106]:
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [108]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(50,71,9).reshape(3,3)

In [109]:
arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [110]:
arr2

array([[59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

In [111]:
np.hstack((arr1,arr2))

array([[16, 11, 13, 59, 56, 64],
       [17, 13, 16, 53, 54, 69],
       [ 3, 16, 11, 69, 63, 50]])

In [112]:
np.vstack((arr1,arr2))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

In [113]:
#ques1

In [114]:
import numpy as np

In [115]:
#ques2

In [116]:
arr1=np.array([1,2,3,4,5])

In [117]:
#ques3

In [118]:
arr2=np.random.randint(1,10,10)

In [119]:
arr2

array([5, 2, 7, 7, 1, 6, 9, 8, 1, 9])

In [120]:
#ques4

In [121]:
arr3=np.random.randint(10,20,10)

In [122]:
arr3

array([19, 12, 12, 15, 18, 13, 19, 15, 19, 19])

In [123]:
#ques5

In [124]:
arr4=np.repeat(5,10)
arr4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [125]:
#ques6

In [126]:
arr5=np.random.randint(1,10,9).reshape(3,3)
arr5

array([[5, 3, 1],
       [8, 1, 5],
       [1, 6, 1]])

In [127]:
#ques7

In [128]:
arr6=np.random.randint(1,10,9)
arr6

array([3, 1, 3, 8, 2, 6, 8, 8, 7])

In [129]:
arr6[arr6%2==0]=0
arr6

array([3, 1, 3, 0, 0, 0, 0, 0, 7])

In [130]:
#ques8

In [131]:
import numpy as np
arr=np.random.rand(9).reshape(3,3)
arr

array([[0.47540615, 0.96596163, 0.14840138],
       [0.09875916, 0.2960424 , 0.63338036],
       [0.52070028, 0.98561029, 0.7530439 ]])

In [132]:
#ques9

In [133]:
import numpy as np
arr1=np.random.randint(1,17,16).reshape(4,4)
arr1
arr2=arr[1:,1:3]
arr2

array([[0.2960424 , 0.63338036],
       [0.98561029, 0.7530439 ]])

In [134]:
#ques10

In [135]:
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(10,19).reshape(3,3)
arr1
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [136]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [138]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [139]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [140]:
#searching array in numpy 

In [141]:
import numpy as np
arr=np.array([10,20,30,40,40,20,40,40])
x=np.where(arr==40)
print(x)

            

(array([3, 4, 6, 7], dtype=int64),)


In [142]:
#searchsorted

In [143]:
import numpy as np
a=np.array([2,5,8,9,13])
x=np.searchsorted(a,7)
print(x)

2


In [144]:
import numpy as np
a=np.array([2,5,8,9,13])
x=np.searchsorted(a,7, side='right')
print(x)

2
